import Head from 'next/head'
import { useEffect, useState } from 'react'
import CubeHeures from '../components/CubeHeures.js'
import CubeSecondes from '../components/CubeSecondes.js'
import CubeMinutes from '../components/CubeMinutes.js'
import styles from '../styles/Home.module.scss'

export default function Home() {

  const [secondes, setSecondes] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [heures, setHeures] = useState(0);

  useEffect( ()=>{
      setTimeout(()=>{
        if (secondes < 59) {
          setSecondes(secondes+1)          
        }
        if (secondes == 59) {
          setSecondes(s => 0)
          setMinutes(m => m+1)
        }
        if (minutes == 59 && secondes == 59) {
          setMinutes(m => 0)
          setHeures(h => h+1)
        }
      }, 1000)
  })

  const mystyle = {
    color: "black",
    fontSize : "75px",
    fontFamily: "Arial"
  };

  function Text({variable}){
    return <p style={mystyle}>{variable}</p>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CubeHeures heures={heures} minutes={minutes} secondes={secondes}/>
        <p>:</p>
        <CubeMinutes minutes={minutes} secondes={secondes}/>
        
        <p>:</p>
        <CubeSecondes secondes={secondes}/>
        
      </main>
    </div>
  )
}
